export enum Types {
    ADD_TO_CART = 'ADD_TO_CART',
    REMOVE_FROM_CART = 'REMOVE_FROM_CART',
    CLEAR_CART = 'CLEAR_CART',
    SET_CART = 'SET_CART',
    SET_PAGINATE = 'SET_PAGINATE',
    SET_CATEGORIES = 'SET_CATEGORIES',
    SET_LOADED = 'SET_LOADED',
    SET_SORT_BY = 'SET_SORT_BY',
    PLUS_CART_ITEM = 'PLUS_CART_ITEM',
    MINUS_CART_ITEM = 'MINUS_CART_ITEM'
}