export enum Types {
    ADD_TO_CART = 'ADD_TO_CART',
    REMOVE_TO_CART = 'REMOVE_TO_CART',
    CLEAR_CART = 'CLEAR_CART',
    SET_CART = 'SET_CART',
    SET_PAGINATE = 'SET_PAGINATE',
    SET_CATEGORIES = 'SET_CATEGORIES',
    SET_LOADED = 'SET_LOADED',
    SET_SORT_BY = 'SET_SORT_BY',
}